# Generated by Django 2.2.13 on 2022-03-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status_listed',
            field=models.BooleanField(default='False'),
        ),
    ]
