# Generated by Django 2.2.13 on 2022-03-22 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_mine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status_closed',
        ),
    ]
