# Generated by Django 2.2.13 on 2022-03-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220322_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status_active',
        ),
        migrations.AddField(
            model_name='listing',
            name='status_closed',
            field=models.BooleanField(default='False'),
        ),
    ]
