# Generated by Django 2.2.13 on 2022-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='finalBid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.BooleanField(default='False'),
        ),
    ]
