# Generated by Django 2.2.13 on 2022-03-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220322_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.BooleanField(default='False'),
        ),
    ]
