# Generated by Django 2.2.13 on 2022-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220322_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
