# Generated by Django 2.2.13 on 2022-03-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220322_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
