# Generated by Django 2.2.13 on 2022-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220322_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winnerStatus',
            field=models.BooleanField(default='False'),
        ),
    ]
